name: 'Hello World'
description: 'A simple hello world GitHub Action'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
runs:
  using: 'node16'
  main: 'dist/index.js'
